name: Deploy MkDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material pymdown-extensions mkdocs-awesome-pages-plugin pyyaml
      - run: python scripts/generate_comparison_index.py
      - run: python scripts/generate_sitemap.py
      - run: mkdocs gh-deploy --force